In [70]:
import pandas as pd
data = {'Roll No':[101,102,103,104,105,107,108],
'Name':['Rahul','Priya','Pooja','Riya','Vanshika','Eva','Kajal'],
        'Department':['BCA','BCA','BCA','MCA','BCA','BCA','BCA'],
        'Age':[20,30,21,22,20,20,20],
        'Marks':[85,56,78,98,99,98,97]
}
df=pd.DataFrame(data)
print("Complete Data:")
print(df)

Complete Data:
   Roll No      Name Department  Age  Marks
0      101     Rahul        BCA   20     85
1      102     Priya        BCA   30     56
2      103     Pooja        BCA   21     78
3      104      Riya        MCA   22     98
4      105  Vanshika        BCA   20     99
5      107       Eva        BCA   20     98
6      108     Kajal        BCA   20     97

In [71]:
print(df.head(3))

   Roll No   Name Department  Age  Marks
0      101  Rahul        BCA   20     85
1      102  Priya        BCA   30     56
2      103  Pooja        BCA   21     78

In [ ]:
print(df.tail(2))

   Roll No   Name Department  Age  Marks
5      107    Eva        BCA   20     98
6      108  Kajal        BCA   20     97

In [ ]:
print(df.shape)

(7, 5)

In [ ]:
print(df.columns)

Index(['Roll No', 'Name', 'Department', 'Age', 'Marks'], dtype='object')

In [ ]:
print(df.dtypes)

Roll No        int64
Name          object
Department    object
Age            int64
Marks          int64
dtype: object

In [72]:
print(df)

   Roll No      Name Department  Age  Marks
0      101     Rahul        BCA   20     85
1      102     Priya        BCA   30     56
2      103     Pooja        BCA   21     78
3      104      Riya        MCA   22     98
4      105  Vanshika        BCA   20     99
5      107       Eva        BCA   20     98
6      108     Kajal        BCA   20     97

In [ ]:
print(df['Name'])

0       Rahul
1       Priya
2       Pooja
3        Riya
4    Vanshika
5         Eva
6       Kajal
Name: Name, dtype: object

In [ ]:
print(df[['Name','Marks']])

       Name  Marks
0     Rahul     85
1     Priya     56
2     Pooja     78
3      Riya     98
4  Vanshika     99
5       Eva     98
6     Kajal     97

In [73]:
print(df[df['Marks']>80])

   Roll No      Name Department  Age  Marks
0      101     Rahul        BCA   20     85
3      104      Riya        MCA   22     98
4      105  Vanshika        BCA   20     99
5      107       Eva        BCA   20     98
6      108     Kajal        BCA   20     97

In [ ]:
print(df[df['Marks']<70])

   Roll No   Name Department  Age  Marks
1      102  Priya        BCA   30     56

In [ ]:
print(df[(df['Marks'] >= 70) & (df['Marks'] <= 90)])

   Roll No   Name Department  Age  Marks
0      101  Rahul        BCA   20     85
2      103  Pooja        BCA   21     78

In [74]:
print(df[df['Department'] == 'BCA'])

   Roll No      Name Department  Age  Marks
0      101     Rahul        BCA   20     85
1      102     Priya        BCA   30     56
2      103     Pooja        BCA   21     78
4      105  Vanshika        BCA   20     99
5      107       Eva        BCA   20     98
6      108     Kajal        BCA   20     97

In [75]:
print(df[df['Age']>20])

   Roll No   Name Department  Age  Marks
1      102  Priya        BCA   30     56
2      103  Pooja        BCA   21     78
3      104   Riya        MCA   22     98

In [ ]:
print(df[df['Marks']>80]['Marks'].max())

99

In [80]:
print(df['Marks'].mean())

87.28571428571429

In [79]:
print(df['Marks'].max())

99

In [78]:
print(df['Marks'].min())

56

In [77]:
print(df['Marks'].median())

97.0

In [76]:
print(df['Marks'].value_counts())

Marks
98    2
85    1
56    1
78    1
99    1
97    1
Name: count, dtype: int64

In [ ]:
print((df['Marks']>75).sum())

6

In [81]:
print(df[df['Department']=='BCA']['Marks'].mean())

85.5

In [ ]:
print(df[df['Department']=='BCA']['Marks'].mean())

85.5

In [82]:
print(df.loc[df['Marks'].idxmax()])

Roll No            105
Name          Vanshika
Department         BCA
Age                 20
Marks               99
Name: 4, dtype: object

In [32]:
df['Bonous']=5
df['Total_Marks'] = df['Marks']+df['Bonous']

In [83]:
df

   Roll No      Name Department  Age  Marks
0      101     Rahul        BCA   20     85
1      102     Priya        BCA   30     56
2      103     Pooja        BCA   21     78
3      104      Riya        MCA   22     98
4      105  Vanshika        BCA   20     99
5      107       Eva        BCA   20     98
6      108     Kajal        BCA   20     97

In [84]:
df['Result']=df['Marks'].apply(lambda x:'Fail' if x <=40 else'Pass'if x <=60 else 'Good' if  x <=80 else'Very Good' if x <90 else 'Excellent')
print(df)

   Roll No      Name Department  Age  Marks     Result
0      101     Rahul        BCA   20     85  Very Good
1      102     Priya        BCA   30     56       Pass
2      103     Pooja        BCA   21     78       Good
3      104      Riya        MCA   22     98  Excellent
4      105  Vanshika        BCA   20     99  Excellent
5      107       Eva        BCA   20     98  Excellent
6      108     Kajal        BCA   20     97  Excellent

In [85]:
print(df.sort_values(by='Marks',ascending=False))

   Roll No      Name Department  Age  Marks     Result
4      105  Vanshika        BCA   20     99  Excellent
3      104      Riya        MCA   22     98  Excellent
5      107       Eva        BCA   20     98  Excellent
6      108     Kajal        BCA   20     97  Excellent
0      101     Rahul        BCA   20     85  Very Good
2      103     Pooja        BCA   21     78       Good
1      102     Priya        BCA   30     56       Pass

In [86]:
print(df.nlargest(3,'Marks'))

   Roll No      Name Department  Age  Marks     Result
4      105  Vanshika        BCA   20     99  Excellent
3      104      Riya        MCA   22     98  Excellent
5      107       Eva        BCA   20     98  Excellent

In [88]:
df['Rank'] = df['Marks'].rank(ascending=False,method='min').astype(int)

In [87]:
df

   Roll No      Name Department  Age  Marks     Result
0      101     Rahul        BCA   20     85  Very Good
1      102     Priya        BCA   30     56       Pass
2      103     Pooja        BCA   21     78       Good
3      104      Riya        MCA   22     98  Excellent
4      105  Vanshika        BCA   20     99  Excellent
5      107       Eva        BCA   20     98  Excellent
6      108     Kajal        BCA   20     97  Excellent

In [90]:
df.groupby('Department').size()

Department
BCA    6
MCA    1
dtype: int64

In [91]:
df.groupby('Department')['Marks'].mean()

Department
BCA    85.5
MCA    98.0
Name: Marks, dtype: float64

In [92]:
df.groupby('Department')['Marks'].max()

Department
BCA    99
MCA    98
Name: Marks, dtype: int64

In [93]:
df.groupby('Department')['Marks'].min()

Department
BCA    56
MCA    98
Name: Marks, dtype: int64

In [95]:
df['Grade']=df['Marks'].apply(lambda x : 'A+' if x >=90 else 'A' if x >=80 else 'B' if x >= 70 else 'c' if x >=60 else 'D')

In [96]:
df

   Roll No      Name Department  Age  Marks     Result  Rank Grade
0      101     Rahul        BCA   20     85  Very Good     5     A
1      102     Priya        BCA   30     56       Pass     7     D
2      103     Pooja        BCA   21     78       Good     6     B
3      104      Riya        MCA   22     98  Excellent     2    A+
4      105  Vanshika        BCA   20     99  Excellent     1    A+
5      107       Eva        BCA   20     98  Excellent     2    A+
6      108     Kajal        BCA   20     97  Excellent     4    A+

In [102]:
merit_list = df[['Rank' ,'Roll No','Department','Marks','Grade','Result']]

In [103]:
merit_list

   Rank  Roll No Department  Marks Grade     Result
4     1      105        BCA     99    A+  Excellent
3     2      104        MCA     98    A+  Excellent
5     2      107        BCA     98    A+  Excellent
6     4      108        BCA     97    A+  Excellent
0     5      101        BCA     85     A  Very Good
2     6      103        BCA     78     B       Good
1     7      102        BCA     56     D       Pass

In [105]:
merit_list = merit_list.sort_values(by='Marks',ascending=False)
merit_list.to_excel('student_merit_list.xlsx',index=False)

In [106]:
from google.colab import files
files.download('student_merit_list.xlsx')